### ISSUE TITLE
Is a release coming?

### ISSUE THREAD

**Issue by AuroraMartell** [niksedk/subtitle-alchemist#1]
As a Subtitle Edit user, this looks interesting, but I'm wondering if there's a release coming.

**Comment by niksedk** [comment]
I'm hoping for an alpha release in a few months... for Windows (I do not have a mac, which is required for making a mac version).

Subtitle Alchemist will be a light version of SE (written in Maui)
I'm working on these features:
- Waveform
- Auto-translation
- Whisper audio to text
- Fix common errors
- Burn-in subtitles
- ....

**Comment by AuroraMartell** [comment]
Good to know! 

How could this new app be used _alongside_ SE?

**Comment by niksedk** [comment]
This could be useful for users on Windows 11 with a high DPI monitor or people who like the WinUI application style (with the back button in the title bar etc.).

Also, mac people might be able to compile and run this.

Teaser screenshot
![image](https://github.com/user-attachments/assets/3c51d01c-56b3-4010-a7e8-c778dcca69c5)


Note: This is not working at all atm. 
I'm just testing too see what's possible in Maui (which seems to have progressed nicely).

**Comment by AuroraMartell** [comment]
Sounds like a fun app! I'm excited to have a look at it when you have an alpha ready.

**Comment by AuroraMartell** [comment]
Oh, and one thing: Will Sub Alchemist have the option to burn in subtitles to a video?

Because this is my current workflow:

- [ ] Download an episode of a show
- [ ] Generate automatic subtitles
- [ ] Translate them using the auto-translate feature
- [ ] Burn the translate sub into the video.

**Comment by niksedk** [comment]
> Oh, and one thing: Will Sub Alchemist have the option to burn in subtitles to a video?
> 
> Because this is my current workflow:
> 
>     * [ ]  Download an episode of a show
> 
>     * [ ]  Generate automatic subtitles
> 
>     * [ ]  Translate them using the auto-translate feature
> 
>     * [ ]  Burn the translate sub into the video.

Burn-in is now on the TODO list :)

**Comment by AuroraMartell** [comment]
> > Oh, and one thing: Will Sub Alchemist have the option to burn in subtitles to a video?
> > Because this is my current workflow:
> > ```
> > * [ ]  Download an episode of a show
> > 
> > * [ ]  Generate automatic subtitles
> > 
> > * [ ]  Translate them using the auto-translate feature
> > 
> > * [ ]  Burn the translate sub into the video.
> > ```
> 
> Burn-in is now on the TODO list :)

Thank you, Nikolaj!
