### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by AuroraMartell** [niksedk/subtitle-alchemist#2]
Hi, I just attempted to install the latest build and got an error message about not being able to identify the signature.

When will this be fixed?

**Comment by niksedk** [comment]
I've updated release with some installation notes - https://github.com/niksedk/subtitle-alchemist/releases/tag/0.0.8.0-Alpha

**Comment by AuroraMartell** [comment]
> I've updated the release with some installation notes - https://github.com/niksedk/subtitle-alchemist/releases/tag/0.0.8.0-Alpha

I followed the steps but it still doesn't work. The _Install_ button is greyed out.

**Comment by niksedk** [comment]
Is this portable version any better?
https://github.com/niksedk/subtitle-alchemist/releases/tag/0.0.0.1-Alpha

Unpack to something like `C:\Tools\SA` (do not install to a write protected folder like `C:\Program files`)

**Comment by AuroraMartell** [comment]
> Is this portable version any better? https://github.com/niksedk/subtitle-alchemist/releases/tag/0.0.0.1-Alpha
> 
> Unpack to something like `C:\Tools\SA` (do not install to a write protected folder like `C:\Program files`)

It works, but trying to use the auto-translate feature makes the app crash.

**Comment by niksedk** [comment]
OK, thx for lettinng me know :)

Alpha updated: https://github.com/niksedk/subtitle-alchemist/releases - so auto-translate might work
